---
name: Expresiones
locale: es
type: learning
beta: false
teacher_info: |-
  ### Objetivos principales

  * Introducir las expresiones como evolución "inteligente" de los literales.
  * Primer acercamiento a programas que dependen del estado inicial del tablero.

  ### Objetivos secundarios

  * Expresiones aritméticas: `+`, `-`, `*`, `div`.
  * Operaciones sobre direcciones: `opuesto`, `siguiente`, `previo`.
  * Operaciones que "leen" el estado del tablero: `nroBolitas`.
language: gobstones
id_format: '%05d'
order:
- 1
- 2
- 3
- 5
- 4
- 6
- 7
- 8
- 9
- 10
- 11
