---
name: Expresiones
locale: es
type: learning
beta: false
teacher_info: |-
  ### Objetivos principales

  * Introducir las expresiones como evolución "inteligente" de los literales.
  * Primer acercamiento a programas que dependen del estado inicial del tablero.

  ### Objetivos secundarios

  * Expresiones aritméticas: `+`, `-`, `*`, `div`, `mod` (no todas).
  * Operaciones sobre direcciones: `opuesto`, `siguiente`, `previo`.
  * Operaciones que "leen" el estado del tablero: `nroBolitas`.
language: gobstones
id_format: '%05d'
order:
- 1
